---
- name: Create VLANS
  hosts: all
  become: yes
  tasks:
    - name: Create VLAN 101 on Cisco iOS devices
      ansible.builtin.pause:
        seconds: 5
    - name: Assigning Ports for VLAN 101
      ansible.builtin.pause:
        seconds: 5
    - name: Configuring Interfaces for VLAN 101
      ansible.builtin.pause:
        seconds: 5
    - name: Configuring DHCP for VLAN 101
      ansible.builtin.pause:
        seconds: 5
    - set_fact:
        LUN_task: "VLAN 101 Created"
    - name: debug
      debug:
        var: LUN_task