---
- name: Create LUN
  hosts: all
  become: yes
  tasks:
    - name: Create 100GB LUN on Netapp ONTAP with name new_volume
      ansible.builtin.pause:
        timeout: 5
    - name: Mapping LUN to VMware
      ansible.builtin.pause:
        timeout: 5
    - name: Refreshing and Scanning VMware Storage
      ansible.builtin.pause:
        timeout: 5
    - name: Formatting Storage as VMFS
      ansible.builtin.pause:
        timeout: 5
    - name: Creating New Datastore
      ansible.builtin.pause:
        timeout: 5