---
- name: Create LUN
  hosts: all
  become: yes
  tasks:
    - name: Create 100GB LUN on Netapp ONTAP with name new_volume
      ansible.builtin.pause:
        seconds: 5
    - set_fact:
        LUN_task: "VLAN 101 Added"
    - name: debug disk_id
      debug:
        var: LUN_task
    - name: Mapping LUN to VMware
      ansible.builtin.pause:
        seconds: 5
    - name: Refreshing and Scanning VMware Storage
      ansible.builtin.pause:
        seconds: 5
    - name: Formatting Storage as VMFS
      ansible.builtin.pause:
        seconds: 5
    - name: Creating New Datastore
      ansible.builtin.pause:
        seconds: 5