---
- name: Create VM
  hosts: all
  become: yes
  tasks:
    - name: Create RHEL VM 
      ansible.builtin.pause:
        seconds: 5
    - name: Deploying HTTPD Webserver
      ansible.builtin.pause:
        seconds: 5
    - name: Copy Website files
      ansible.builtin.pause:
        seconds: 5
    - name: Start and enable httpd
      ansible.builtin.pause:
        seconds: 5
    - name: Configure firewall
      ansible.builtin.pause:
        seconds: 5
    - set_fact:
        LUN_task: "New Virtual Machine has been created"
    - name: debug
      debug:
        var: LUN_task